INSERT INTO subcategories (subcategory, category_id) 
VALUES 
('Action Movies', 1),
('Musicals', 1),
('Comedies', 1),
('Actors', 1),
('Mysteries', 1),

('Capitals', 2),
('Famous Canadians', 2),
('Canadian Brand Names', 2),
('Provinces and Territories', 2),
('Prime Ministers', 2),

('Mountain Ranges', 3),
('Countries', 3),
('Capital Cities', 3),
('Islands', 3),
('European Countries', 3),

('Fruits and Vegetables', 4),
('Pizza Toppings', 4),
('Desserts', 4),

('Pokemon', 5),
('First Person Shooters', 5),
('Third Person Shooters', 5),
('Turn Based Games', 5),
('Gaming Terms', 5),
('Side Scrollers', 5),
('Consoles', 5),
('Protagonists', 5),
('Bad Guys', 5),
('Nintendo Characters', 5),
('MOBA Characters', 5),
('Famous Items', 5),
('Games You Own', 5),
('Multiplayer Games', 5),
('Fighting Games', 5),
('Things you say while playing', 5),
('Fighting Game Characters', 5),
('Locations', 5),
('Genres', 5),

('Anything', 6),

('Trees', 7),
('Flowers', 7),
('Any Plant', 7),

('Genres', 8),
('Lead Singers', 8),
('Musical Instruments', 8),
('The 80''s', 8),
('The 90''s', 8),

('Fictional Characters', 9),
('Menu Items', 9),
('Magazines', 9),
('Items You Save Up To Buy', 9),
('Footwear', 9),
('Something you Keep Hidden', 9),
('Items in a Suitcase', 9),
('Things With Tails', 9),
('Sports Equipment', 9),
('Crimes', 9),
('Famous Duos and Trios', 9),
('Things Found In A Desk', 9),
('Vacation Spots', 9),
('Items in a Vending Machine', 9),
('Movie Titles', 9),
('Games', 9),
('Things that You Wear', 9),
('Beers', 9),
('Things at a Circus', 9),
('Atheletes', 9),
('Four Letter Words', 9),
('Items in the Fridge', 9),
('Farm Animals', 9),
('Things at the Beach', 9),
('Colours', 9),
('Tools', 9),
('Boys Names', 9),
('Things That Are Cold', 9),
('Insects', 9),
('Breakfast Foods', 9),
('Product Names', 9),
('World Leaders', 9),
('School Subjects', 9),
('Ice Cream Flavours', 9),
('Fruits', 9),
('Toys', 9),
('Authors', 9),
('Halloween Costumes', 9),
('Weapons', 9),
('Things that are Round', 9),
('Musical Instruments', 9),
('Cartoon Characters', 9),
('Things that Have Stripes', 9),
('Animals', 9),
('Spicy Food', 9),
('Girls Names', 9);